enable output to directory and search for files recursively
owenstranathan/bash-templater pull request #3
Opened 2020-02-05 10:50 UTC by slinstaedt

If you are interested... used this for creating configuration files during docker container creation.

2020-02-05 19:32 UTC, owenstranathan requested changes
I made a PR with the changes I wanted to see you your fork. If you merge that into your fork then I'll merge it into mine 👍

2020-02-05 19:32 UTC, owenstranathan commented on templater.sh
> +    if [ -z "$output" ]; then
I don't love that this disables echo by default, should be another option

2020-02-05 19:32 UTC, owenstranathan commented on templater.sh
> +        mkdir -p $(dirname "$output/$template_path")
This subshell should be quoted to avoid word splitting

2020-02-05 19:32 UTC, owenstranathan commented on templater.sh
> +        templates=$(find "$template_path")
using this without `read -a` won't always work. prefer bash4 globstar

2020-02-05 19:32 UTC, owenstranathan commented on templater.sh
> +        templates="$template_path/"*
this used to be `templates=( "$template_path/"* )` which made it an array.
Now it's just the first file from the glob. That broken :(

2020-02-06 20:34 UTC, slinstaedt commented
I am by far not an export for shell scripting, so any improvements are welcome.

2020-02-06 20:37 UTC, owenstranathan commented
That's the beautiful thing about bash, it's so complex and terrible that we're all equal under it's umbrella of untenability.

2020-02-06 20:38 UTC, merged